### ISSUE TITLE
Rollback changes

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-signer#260]
Users might want to reset their changes and reset the source collection data to the same as the destination.

**Comment by mcomella** [comment]
For a specific issue I ran into that rollback could have fixed:
- Create a record
- Request review
- (Reviewer specifies record should be two records with different names)

Ideally, I could revert my state and rewrite my commit. However, instead, I had to:
- Delete record
- Create 2 new records

And the review request diff shows +2 -1 (create, delete, create 2x) rather than the absolute changes between the current state and the end state +2 (create 2x).
